package algo

func TestAlgo() {
	// testTreeBFS()
	// testTreeDFS()
	// testInequality()
	// testPower()
	// testIntDivide()
	// testNewtonSqrt()
	// testGraphBFS()
	// testSpiralWalk()
	// testGetIndex()
	// testPadString()
	// testBinSort()
	// testDigitsNumber()
	// testNextHigherInArr()
	// testNextHigherNum()
	// testSquarePro()
	// testGCD()
	// testBinarySearch()
	// testCountingSort()
	// testRadixSort()
	// testPartitionInt()
	// testQuicksortInt()
	// testMatAt()
	// testSaddlebackSearchL()
	// testSaddlebackSearch()
	// testSuffixArray()
	// testPartitionStr()
	// testQuicksortStr()
	// testCompareStr()
	// testLRSeq()
	// testPermutations()
	// testSubsets()
	testCombinations()
}

func AllTests() {
	testTreeBFS()
	testTreeDFS()
	testInequality()
	testPower()
	testIntDivide()
	testNewtonSqrt()
	testGraphBFS()
	testSpiralWalk()
	testGetIndex()
	testPadString()
	testBinSort()
	testDigitsNumber()
	testNextHigherInArr()
	testNextHigherNum()
	testSquarePro()
	testGCD()
	testBinarySearch()
	testCountingSort()
	testRadixSort()
	testPartitionInt()
	testQuicksortInt()
	testMatAt()
	testSaddlebackSearchL()
	testSaddlebackSearch()
	testSuffixArray()
	testPartitionStr()
	testQuicksortStr()
	testCompareStr()
	testLRSeq()
	testPermutations()
	testSubsets()
	testCombinations()
}
