package algo

func TestAlgo() {
	// testTreeBFS()
	// testTreeDFS()
	// testInequality()
	// testPower()
	// testIntDivide()
	// testNewtonSqrt()
	// testGraphBFS()
	// testSpiralWalk()
	// testGetIndex()
	// testPadString()
	// testBinSort()
	// testDigitsNumber()
	// testNextHigherInArr()
	// testNextHigherNum()
	// testSquarePro()
	// testGCD()
	// testBinarySearch()
	// testCountingSort()
	// testRadixSort()
	// testPartition()
	// testQuicksort()
	// testMatAt()
	// testSaddlebackSearchL()
	testSaddlebackSearch()
}

func AllTests() {
	testTreeBFS()
	testTreeDFS()
	testInequality()
	testPower()
	testIntDivide()
	testNewtonSqrt()
	testGraphBFS()
	testSpiralWalk()
	testGetIndex()
	testPadString()
	testBinSort()
	testDigitsNumber()
	testNextHigherInArr()
	testNextHigherNum()
	testSquarePro()
	testGCD()
	testBinarySearch()
	testCountingSort()
	testRadixSort()
	testPartition()
	testQuicksort()
	testMatAt()
	testSaddlebackSearchL()
	testSaddlebackSearch()
}
